version: '3'

networks:
  networks_bridge:
    driver: bridge

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
      - ./blogdb.sql:/docker-entrypoint-initdb.d/blogdb.sql
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - networks_bridge

  # my project
  project:
    build: ./client
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - networks_bridge

  #  my scripts
  scripts:
    build: ./testdb
    depends_on:
      - db
    networks:
      - networks_bridge

  # my forum
  phpbb:
    build: ./forum
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - networks_bridge
volumes:
  data-volume: 