version: "3.9"
services:

  # my project
  project:
    build: /client
    ports:
      - "3000:3000"
    depends_on:
      - db

  # my database
  db:
    build: /database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3030:3030"

  #  my scripts
  scripts:
    build: /testdb
    depends_on:
      - db

  # my forum
  phpbb:
    build: /forum
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
