imports:
    - { resource: parameters.yml }

services:
    acme.demo.controller.main:
        class: acme\demo\controller\main_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    acme.demo.controller.acp:
        class: acme\demo\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    acme.demo.controller.mcp:
        class: acme\demo\controller\mcp_controller
        arguments:
            - '@language'
            - '@request'
            - '@template'

    acme.demo.controller.ucp:
        class: acme\demo\controller\ucp_controller
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'

    acme.demo.service:
        class: acme\demo\service
        arguments:
            - '@user'
            - '%acme.demo.tables.demo_table%'

    acme.demo.listener:
        class: acme\demo\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    acme.demo.command.sample:
        class: acme\demo\console\command\sample
        arguments:
            - '@user'
        tags:
            - { name: console.command }

    acme.demo.cron.task.sample:
        class: acme\demo\cron\task\sample
        arguments:
            - '@config'
        calls:
            - [set_name, [cron.task.acme.demo.sample]]
        tags:
            - { name: cron.task }

    acme.demo.notification.type.sample:
        class: acme\demo\notification\type\sample
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
