# Use the official PHP image as the base image
FROM php:8.1-apache

# Install necessary packages and extensions
RUN apt-get update && \
    apt-get install -y \
    git \
    unzip \
    libzip-dev && \
    docker-php-ext-install zip

# Set the working directory to /var/www/html
WORKDIR /var/www/html

# Copy the project files to the container
COPY . /var/www/html/forum

# Set the Apache document root to the project directory
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Expose port 80 for the web server
EXPOSE 80

# Start the Apache web server when the container starts
CMD ["apache2-foreground"]
